// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCampus.DataAccess;

#nullable disable

namespace SmartCampus.DataAccess.Migrations
{
    [DbContext(typeof(CampusDbContext))]
    [Migration("20251215120000_AddCourseTypeAndDepartmentRequirements")]
    partial class AddCourseTypeAndDepartmentRequirements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // Note: This is a simplified designer file.
            // The full designer file should be generated by Entity Framework.
            // This file ensures the migration can be recognized.
#pragma warning restore 612, 618
        }
    }
}

